.PHONY:clean

CC=g++
CFLAGS=-Wall -Wextra

aarect_light: aarect_light.cpp
	$(CC) $(CFLAGS) -o aarect_light aarect_light.cpp

cornell_box: cornell_box.cpp
	$(CC) $(CFLAGS) -o cornell_box cornell_box.cpp

clean:
	rm -f aarect_light cornell_box