.PHONY=clean

CC=g++
CFLAGS=-Wall -Wextra -pedantic -std=c++17 -g


shiny_matt_spheres: shiny_matt_spheres.cpp
	$(CC) $(CFLAGS) -o shiny_matt_spheres shiny_matt_spheres.cpp

clean:
	rm -f shiny_matt_spheres