.PHONY=clean

CC=g++
CFLAGS=-Wall -Wextra -Werror -pedantic -std=c++17 -g

ppm_format: PPM_format.cpp
	$(CC) $(CFLAGS) -o ppm_format PPM_format.cpp

ppm_image: PPM_image.cpp
	$(CC) $(CFLAGS) -o ppm_image PPM_image.cpp
